version: "3.9"

services:
  simulador-api:
    container_name: simulador-api
    build:
      context: ./Simulador.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mantém banco SQLite fora do container (persistência)
      - ./Simulador.Api/Data:/app/Data
    environment:
      # Pode ser lido no Program.cs se quiser
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
